# Generated by Django 3.1.7 on 2021-04-05 06:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel_tracker', '0003_auto_20210405_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='unique_squirrel_id',
            field=models.CharField(help_text='Unique Squirrel ID', max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]+[A-Z]-[AP]M-[0-9]{4}-[0-9]{2}$', code='invalid_id', message='Incorrect format of Unique Squirrel ID')]),
        ),
    ]
